#ifndef DISPLAY_H
#define DISPLAY_H

#define CELL_SIZE 50
#define CELL_MARGIN 5
#define GRID_SIZE (CELL_SIZE * 9)
#define FONT_SIZE (CELL_SIZE - CELL_MARGIN * 2)
#define MENU_SIZE (CELL_SIZE * 4)
#define WINDOW_WIDTH (GRID_SIZE + MENU_SIZE)
#define WINDOW_HEIGHT (GRID_SIZE)

#endif